name: mi_card
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
   - images/nakano.jpg

  fonts:
   - family: Pacifico
     fonts:
      - asset: fonts/Pacifico-Regular.ttf

   - family: M PLUS
     fonts:
      - asset: fonts/MPLUSRounded1c-Black.ttf
      - asset: fonts/MPLUSRounded1c-Bold.ttf
      - asset: fonts/MPLUSRounded1c-ExtraBold.ttf
      - asset: fonts/MPLUSRounded1c-Light.ttf
      - asset: fonts/MPLUSRounded1c-Medium.ttf
      - asset: fonts/MPLUSRounded1c-Regular.ttf
      - asset: fonts/MPLUSRounded1c-Thin.ttf